Apply package-lint/elisp-checkdoc suggestions
magnars/dash.el pull request #327
Opened 2019-12-03 01:45 UTC by conao3

Hi! I found this package and found many package-lint/elisp-checkdoc errors.
So I fix them to fix easy as my first contribution step.

### before
478 erros/warnings
```emacs-lisp
 dash.el     1   1 warning         Including "Emacs" in the package summary is usually redundant. (emacs-lisp-package)
 dash.el     1   1 error           Package should have a Homepage or URL header. (emacs-lisp-package)
 dash.el     1  54 warning         You should depend on (emacs "24") if you need lexical-binding. (emacs-lisp-package)
 dash.el     7   4 warning         You should include standard keywords: see the variable `finder-known-keywords'. (emacs-lisp-package)
 dash.el    29     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el    30     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el    40  15 warning         Replace deprecated `cl' with `cl-lib'.  The `cl-libify' package can help with this. (emacs-lisp-package)
 dash.el    48     warning         All variables and subroutines might as well have a documentation string (emacs-lisp-checkdoc)
 dash.el    53     warning         First line is not a complete sentence (emacs-lisp-checkdoc)
 dash.el    59   1 error           "!cons" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el    63   1 error           "!cdr" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el    67   1 error           "--each" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el    68     warning         Argument ‘list’ should appear (as LIST) in the doc string (emacs-lisp-checkdoc)
 dash.el    80   1 error           "-doto" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el    82     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el    83     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el    95   1 error           "--doto" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el    96     warning         Argument ‘eval-initial-value’ should appear (as EVAL-INITIAL-VALUE) in the doc string (emacs-lisp-checkdoc)
 dash.el   103   1 error           "-each" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   104     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   109   1 error           Aliases should start with the package's prefix "dash". (emacs-lisp-package)
 dash.el   111   1 error           "-each-indexed" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   112     warning         Some lines are over 80 columns wide (emacs-lisp-checkdoc)
 dash.el   120   1 error           "--each-while" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   121     warning         Argument ‘list’ should appear (as LIST) in the doc string (emacs-lisp-checkdoc)
 dash.el   135   1 error           "-each-while" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   142   1 error           "--each-r" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   143     warning         Argument ‘list’ should appear (as LIST) in the doc string (emacs-lisp-checkdoc)
 dash.el   160   1 error           "-each-r" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   161     warning         Second line should not have indentation (emacs-lisp-checkdoc)
 dash.el   165   1 error           "--each-r-while" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   166     warning         Argument ‘list’ should appear (as LIST) in the doc string (emacs-lisp-checkdoc)
 dash.el   180   1 error           "-each-r-while" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   185   1 error           "--dotimes" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   186     warning         Argument ‘num’ should appear (as NUM) in the doc string (emacs-lisp-checkdoc)
 dash.el   186     warning         Probably "executes" should be imperative "execute" (emacs-lisp-checkdoc)
 dash.el   196   1 error           "-dotimes" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   197     warning         Argument ‘num’ should appear (as NUM) in the doc string (emacs-lisp-checkdoc)
 dash.el   197     warning         Probably "calls" should be imperative "call" (emacs-lisp-checkdoc)
 dash.el   202   1 error           "-map" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   206   1 error           "--map" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   207     warning         Argument ‘form’ should appear (as FORM) in the doc string (emacs-lisp-checkdoc)
 dash.el   211   1 error           "--reduce-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   212     warning         Argument ‘form’ should appear (as FORM) in the doc string (emacs-lisp-checkdoc)
 dash.el   218   1 error           "-reduce-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   219     warning         First line is not a complete sentence (emacs-lisp-checkdoc)
 dash.el   221     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   230   1 error           "--reduce" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   231     warning         Argument ‘form’ should appear (as FORM) in the doc string (emacs-lisp-checkdoc)
 dash.el   239   1 error           "-reduce" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   240     warning         First line is not a complete sentence (emacs-lisp-checkdoc)
 dash.el   241     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   243     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   254   1 error           "--reduce-r-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   255     warning         Argument ‘form’ should appear (as FORM) in the doc string (emacs-lisp-checkdoc)
 dash.el   259   1 error           "-reduce-r-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   260     warning         First line is not a complete sentence (emacs-lisp-checkdoc)
 dash.el   261     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   270   1 error           "--reduce-r" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   271     warning         Argument ‘form’ should appear (as FORM) in the doc string (emacs-lisp-checkdoc)
 dash.el   275   1 error           "-reduce-r" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   277     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   278     warning         There should be two spaces after a period (emacs-lisp-checkdoc)
 dash.el   292   1 error           "-reductions-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   293     warning         Argument ‘fn’ should appear (as FN) in the doc string (emacs-lisp-checkdoc)
 dash.el   300   1 error           "-reductions" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   301     warning         Argument ‘fn’ should appear (as FN) in the doc string (emacs-lisp-checkdoc)
 dash.el   308   1 error           "-reductions-r-from" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   309     warning         Argument ‘fn’ should appear (as FN) in the doc string (emacs-lisp-checkdoc)
 dash.el   316   1 error           "-reductions-r" doesn't start with package's prefix "dash". (emacs-lisp-package)
 dash.el   317     warning         Argument ‘fn’ should appear (as FN) in the doc string (em [...]

2019-12-07 16:14 UTC, Fuco1 requested changes

2019-12-07 16:14 UTC, Fuco1 commented on dash.el
> +  "Return a new list of the items in LIST for which PRED return nil.
This is not proper english, unfortunatelly the check is not smart enough to see that.  Only the first "return" should be imperative.

2019-12-07 16:14 UTC, Fuco1 commented on dash.el
> +Note that because 'nil represents a list of zero elements (an
maybe remove the `'` also.  Not sure which is better but since nobody quotes `nil` maybe it shouldn't be.

2019-12-07 16:14 UTC, Fuco1 commented on dash.el
> +  "Return the tail of LIST starting from the first item for which (PRED item) return nil."
should be conjugated, see previous comment.

2019-12-07 16:14 UTC, Fuco1 commented on dash.el
> +  "Return non-nil if SYMBOL is a symbol and start with _."
should be conjugated, see previous comment

2019-12-07 16:14 UTC, Fuco1 commented on dash.el
> +  "Return a lambda which destructures its input as MATCH-FORM and execute BODY.
I'm not going to comment on this anymore, but go through it and put back to third person (-s) those where it is gramatically necessary.

2019-12-07 16:14 UTC, Fuco1 commented
Unfortunatelly the "use imperative" lint has extremely bad false-positive ratio.  Practically more than 50% of the fixes you made are now gramatically incorrect.  I don't know how to silence that particular check, but it's quite useless :(

2019-12-08 02:03 UTC, conao3 commented
I'm not an English native, I misjudged package-lint suggestion. Revert them.
And use `nil` instead `'nil` in all dash.el

2019-12-08 13:33 UTC, Fuco1 commented
No problem! I understand it might get confusing, especially since the official linter suggests what is not proper english :(

2026-01-03 23:09 UTC, conao3 commented
outdated. close.

2026-01-03 23:09 UTC, closed without merging